#!/usr/bin/env bash
set -e
set -x

jitsu deploy

ACCESS_TOKEN=ffffffffffffffffffffffffffffffff
ENVIRONMENT=production
LOCAL_USERNAME=`whoami`
REVISION=`git log -n 1 --pretty=format:"%H"`

curl https://submit.ratchet.io/api/1/deploy/ \
  -F access_token=$ACCESS_TOKEN \
  -F environment=production \
  -F revision=$REVISION \
  -F local_username=$LOCAL_USERNAME
